import { useLocation, useNavigate } from "react-router-dom";
import ScoreCard from "../components/ScoreCard";
import TipsList, { type ApiTip } from "../components/TipsList";

interface LocationState {
  score: number;
  tips: ApiTip[];
  fileName: string;
}

const ResultPage = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const state = location.state as LocationState | null;

  const handleGoBack = () => {
    navigate("/");
  };

  if (!state) {
    return (
      <div className="min-h-screen bg-noise relative flex items-center justify-center">
        <div className="relative z-10 text-center space-y-6 animate-fade-in-up">
          <div className="w-20 h-20 mx-auto rounded-3xl bg-surface-light border border-border flex items-center justify-center">
            <svg className="w-10 h-10 text-foreground-muted" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          </div>
          <h1 className="text-2xl font-semibold text-foreground">No resume processed yet</h1>
          <p className="text-foreground-muted max-w-md mx-auto">
            Upload your resume on the landing page to get started with the analysis.
          </p>
          <button
            onClick={handleGoBack}
            className="px-8 py-3.5 rounded-2xl font-medium bg-primary text-primary-foreground hover:shadow-glow-primary hover:-translate-y-0.5 transition-all duration-300 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 focus:ring-offset-background"
          >
            Go to Upload
          </button>
        </div>
      </div>
    );
  }

  const { score, tips, fileName } = state;

  return (
    <div className="min-h-screen bg-noise relative">
      <div className="relative z-10 container mx-auto px-4 py-8 md:py-12">
        {/* Header */}
        <div className="flex items-center gap-4 mb-8 animate-fade-in-up">
          <button
            onClick={handleGoBack}
            className="p-2 rounded-xl border border-border bg-surface-light text-foreground-muted hover:text-foreground hover:bg-surface transition-all duration-300 focus:outline-none focus:ring-2 focus:ring-primary"
            aria-label="Go back"
          >
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
            </svg>
          </button>
          <div>
            <h1 className="text-xl font-semibold text-foreground">Analysis Results</h1>
            <p className="text-sm text-foreground-muted">{fileName}</p>
          </div>
        </div>

        {/* Content grid */}
        <div className="grid lg:grid-cols-3 gap-6 lg:gap-8">
          {/* Score card - takes 1 column on desktop */}
          <div className="lg:col-span-1 animate-fade-in-up-delay-1">
            <ScoreCard score={score} />
          </div>
          
          {/* Tips list - takes 2 columns on desktop */}
          <div className="lg:col-span-2 animate-fade-in-up-delay-2">
            <TipsList tips={tips} />
          </div>
        </div>

        {/* Print-only header */}
        <div className="hidden print:block mb-8">
          <h1 className="text-3xl font-bold text-black mb-2">Resume Analysis Report</h1>
          <p className="text-gray-600">Generated by ResumeAI</p>
        </div>
      </div>
    </div>
  );
};

export default ResultPage;
